services:

  arengi.psr17:
    class: Nyholm\Psr7\Factory\Psr17Factory
    public: true

  arengi.buzz.client:
      class: Buzz\Client\FileGetContents
      arguments : ["@arengi.psr17"]
      public: true

  arengi.buzz:
      class: Buzz\Browser
      arguments: ["@arengi.buzz.client", "@arengi.psr17"]
      public: true


