<?php
/**
 * Created by PhpStorm.
 * User: johann
 * Date: 20/03/19
 * Time: 14:39
 */

namespace ArengiBuzzBundle;


use ArengiBuzzBundle\DependencyInjection\WrapperBuzzExtension;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class ArengiBuzzBundle extends Bundle
{
    public function getContainerExtension()
    {
        return new WrapperBuzzExtension(); // TODO: Change the autogenerated stub
    }
}